# Numpy 배열 생성 함수와 shape 변환 함수

- 정해진 크기 배열 생성 함수

In [7]:
# zeros 함수는 배열의 모든 원소크기를 0로 지정해준 크기의 배열을 생성합니다,

import numpy as np

A = np.zeros((2,3))
A, A.shape , A.dtype

(array([[0., 0., 0.],
        [0., 0., 0.]]), (2, 3), dtype('float64'))

In [8]:
# ones 함수는 배열의 모든 원소크기를 1로 지정해준 크기의 배열을 생성합니다,

B = np.ones((2,3))
B , B.shape , B.dtype

(array([[1., 1., 1.],
        [1., 1., 1.]]), (2, 3), dtype('float64'))

In [11]:
# empty 함수는 초기화되지 않도록 지정한 크기의 배열을 생성합니다.

C = np.empty((5,5))
C, C.shape, C.dtype

(array([[6.79038653e-313, 2.33419537e-312, 2.44029516e-312,
         1.15928874e-309, 9.70091596e-310],
        [1.02229269e-309, 1.08289689e-309, 1.01397447e-309,
         6.79038882e-313, 1.05140647e-309],
        [9.46240363e-310, 6.79038888e-313, 1.00149713e-309,
         1.09596839e-309, 1.15954338e-309],
        [6.79038907e-313, 9.46240363e-310, 6.79038905e-313,
         1.07534259e-309, 6.79038905e-313],
        [1.04947546e-309, 9.71195034e-310, 9.33678374e-313,
         2.22507386e-306, 4.94065646e-322]]), (5, 5), dtype('float64'))

In [12]:
# random 함수는 0~1 사이의 무작위 값으로 채워진 지정한 크기의 배열을 생성합니다.

D = np.random.random((3,3))
D


array([[0.70856095, 0.94988745, 0.908329  ],
       [0.21771405, 0.31160331, 0.02305907],
       [0.94494885, 0.31156358, 0.51839222]])

In [13]:
# 1~9 사이의 무작위 값을 생성하여 크기 2x2 배열의 원소로 사용

E = np.random.randint(1,10,(5,5))
E

array([[5, 9, 2, 1, 3],
       [1, 3, 4, 3, 8],
       [7, 1, 6, 2, 5],
       [6, 6, 1, 9, 2],
       [9, 3, 9, 1, 4]])

- 연속 원소 배열 생성 함수
    - np.arange(시작 값, 마지막 값, 간격)
    - np.arange(시작 값, 마지막 값)
    - np.arange(마지막 값)
    
연속적인 원소를 가진 배열을 생성할 때 사용, 시작 값부터 지정한 간격으로 배열된 원소 생성, 마지막 값은 범위에서 제외

In [14]:
# 0 <= x < 50 범위 내에서 5 간격으로 숫자를 뽑아 배열을 생성.
A = np.arange(0,50,5)
A

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
# 0,1 <= x < 5 범위 내에서 1 간격으로 뽑아서 배열 생성
# 간격을 적지 않으면 디폴드 값은 1.
B,C = np.arange(0.1,5.1),np.arange(0.1,5.2)
B, C

(array([0.1, 1.1, 2.1, 3.1, 4.1]), array([0.1, 1.1, 2.1, 3.1, 4.1, 5.1]))

In [20]:
# 0 <= x < 10 범위 내에서 배열을 생성
# 시작 값, 간격을 적지 않으면 디폴트 값을 사용합니다, (시작 값 0, 간격 1).
D = np.arange(5)
D

array([0, 1, 2, 3, 4])

- linspace 함수
    - linspace 함수는 지정한 범위 내에 원하는 원소 개수로 숫자를 뽑아서 배열 생성을 합니다.
    - 시작 값 <= x < 마지막 값 범위 내에서 일정한 간격으로 지정한 개수만큼 샘플을 뽑아 배열을 생성합니다.

In [22]:
# 0 <= x < 10 범위 내에 일정한 간격으로 10개의 샘플을 뽑아 배열 생성
A = np.linspace(0, 10, 10)
A

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [23]:
A.size

10

In [24]:
# 샘플링 개수를 지정하지 않으면 디폴트 값은 50,
B = np.linspace(0,100)
B

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

In [25]:
B.size

50

- shape 변환 함수,  
    배열의 shape를 변경할 수 있는 함수, reshape 메소드는 배열의 데이터를 공유하는 shape가 다른 배열인 View를 생성합니다, 원본 배열의 데이터를 공유하지 않는 새로운 복사본을 만들고 싶으면 copy 메소드를 사용해야 합니다.

In [26]:
# 0 ~ 15까지의 16개 원소로 이루어진 1차원 배열 A생성
A = np.arange(16)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
B = A.reshape(4,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
B.shape

(4, 4)

In [29]:
# 다른 배열의 데이터를 공유하고 있는 뷰일 경우 해당 배열이 출력 된다.
A.base

In [30]:
B.base

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [31]:
# A와 B.base 는 동일한 객체 인가?
A is B.base

True

In [32]:
A == B.base

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

- B는 A의 데이터를 공유합니다.
- 정확히는 배열 A의 데이터가 저장되어 있는 메모리 공간을 공유합니다.

In [34]:
# 배열 A와 배열 B는 같은 데이터를 공유하고 있기 때문에, 어느 한쪽을 변경하면 A,B모두 반영됩니다.
# 배열 B의 첫 번째 행을 모두 -1로 변경하면 배열 A와 B모두 반영됩니다.

B[0] = -1
A,B

(array([-1, -1, -1, -1,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]),
 array([[-1, -1, -1, -1],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [43]:
# reshape 메소드를 사용하여 배열 B의 데이터를 공유하는 shape가 (2,8) 인 뷰를 생성후 copy 메소드를 사용하여 뷰의 데이터 복사본을 새로운 
# 메모리 공간에 만듭니다.


C = B.reshape(2,8).copy()
C

array([[-1, -1, -1, -1,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [44]:
C.shape

(2, 8)

In [45]:
C.base
# C.base는 배열 B의 뷰가 아니기 떄문에 아무것도 출력되지 않는다,

In [46]:
B.base

array([-1, -1, -1, -1,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
# 배열 C는 배열 B의 뷰가 아니기 때문에, 배열 C의 데이터 변경이 배열 B에 영향을 주지 못함
C[0] = 0
B, C

(array([[-1, -1, -1, -1],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]), array([[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]))

In [49]:
C is B.base

False

차원을 -1로 적으면 배열의 전체 원소 개수와 확정된 차원 크기로 부터 남은 차원의 크기를 추론하여 배열을 생성

In [50]:
C = np.arange(16)
C

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [52]:
# 변환될 배열의 8로 지정하고 행은 -1로 지정하면 자동으로 행의 수가 계산됩니다.
D = C.reshape(8, -1)

# 자동으로 계산된 크기 8x2인 배열로 변환됩니다.
D, D.shape

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]), (8, 2))

In [53]:
E = C.reshape(-1,8)
E, E.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]]), (2, 8))

In [54]:
# -1은 한번만 사용이 가능 하다.
F = C.reshape(2,-1,-1)

ValueError: can only specify one unknown dimension

- ravel 메소드
    - ravel 메소드는 배열을 1차원 배열로 변환하여 return
   

In [55]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [56]:
A.shape

(2, 2)

In [57]:
B = A.ravel()
B

array([1, 2, 3, 4])

In [58]:
B.shape

(4,)

In [59]:
A[0] = 1

In [60]:
B

array([1, 1, 3, 4])

In [61]:
B.base
# 배열 B는 뷰이기 때문에 공유해준 배열이 출력된다.

array([[1, 1],
       [3, 4]])

In [62]:
B.base is A

True

- resize 메소드
    - resize 메소드는 뷰를 생성하지 않고, 배열의 shape를 직접 바꾼다.

In [67]:
A = np.arange(12)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [74]:
A.resize(3,4)
A

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [77]:
B = A.resize(2,6)
B
# 아무것도 출력 안합니다.

In [76]:
B = A.reshape(3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- newaxis 메소드는 배열의 차원을 증가시켜준다.
- 1차원 배열을 열벡터 또는 행벡터로 바꿀때 사용,

In [83]:
a = np.array([1,2,3])
a = a[:np.newaxis]
a

array([1, 2, 3])

In [84]:
# , 의 차이
b = np.array([1,2,3])
b = b[:,np.newaxis]
b

array([[1],
       [2],
       [3]])

In [93]:
a.shape, b.shape

((3,), (3, 1))

In [95]:
c = np.array([1,2,3])
c = c[np.newaxis, : ]
c

array([[1, 2, 3]])

In [96]:
c.shape

(1, 3)