# 행렬의 정의

In [15]:
# 2 x 3 행렬 A 는 2개의 행과 3개의 열로 구성되어있다.
# 벡터도 행렬이다. 하나의 행으로 구성된 행렬 a를 행벡터라 하고,
# 하나의 열로 구성된 행렬 b를 열벡터라 한다.
import numpy as np

# 2 x 3 행렬 a
a = np.arange(1,7).reshape(2,3)
print(a)

# 행벡터 b
b = np.array([1,2,3])
print(b)

# 열벡터 c
c = np.array([1,2,3])
c.shape = (3, 1)
print(c)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[[1]
 [2]
 [3]]


In [20]:
# 두 행렬의 행의 수와 열의 수가 같을 때 두 행렬의 크기가 같다고 한다. 두 행렬 A,B가 같으려면 두 행렬의 크기가 같으며 대응하는 원소가 모두 같아야 한다.

A = np.array([[1,2], [3,4]])
B = np.array([[1,2], [3,4]])
C = np.array([[1,3], [4,4]])

# == 연산자를 사용하여 원소별로 비교결과 리턴
print(A == B)
print(A == C)

# all 메소드를 사용하여 두 행렬이 같은지 리턴
print((A==B).all())
print((A==C).all())

[[ True  True]
 [ True  True]]
[[ True False]
 [False  True]]
True
False


In [25]:
# 행을 구성하는 열벡터와 행벡터를 구하는 방법
import numpy as np

A = np.array([[1,2,3,4],[5,6,7,8]])
A

# 행렬 A를 구성하는 행벡터들 출력
print(A[0,:]) # A[0]
print(A[1,:]) # A[1]

# 행렬 A를 구성하는 열벡터들 출력
print(A[:,0])
print(A[:,1])
print(A[:,2])
print(A[:,3])

[1 2 3 4]
[5 6 7 8]
[1 5]
[2 6]
[3 7]
[4 8]


In [32]:
len(A[:,]), len(A[0,:]) , 

(2, 4)

### 전치

행렬을 구성하는 원소의 열 인덱스와 행 인덱스를 바꾸는 것을 전치라 한다.

In [37]:
# 넘파이에선 전치 연산을 'transpose 함수' 또는 넘파이 배열의 T 메소드를 사용한다.
import numpy as np

X = np.arange(1,7).reshape(3,2)
print(X,X.shape ,"\n")

print(X.T, X.T.shape ,"\n" )

np.transpose(X)

[[1 2]
 [3 4]
 [5 6]] (3, 2) 

[[1 3 5]
 [2 4 6]] (2, 3) 



array([[1, 3, 5],
       [2, 4, 6]])

### 항등 행렬과 역행렬

대각선 원소만 1이고 나머지는 0인 행렬을 __'항등 행렬(identity matrix)'__ 라고 한다.

In [49]:
# 넘파이에서는 'eye 함수'를 사용하여 항등 해열ㄹ을 만든다
# 항등행렬에 어떤 값을 곱하면 그대로 자기 자신값을 갖습니다.

import numpy as np

I = np.eye(3)

In [50]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [51]:
A = np.arange(9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
print((np.dot(A,I) == A).all())
print((np.dot(I,A) == A).all())

True
True


### 역행렬

역행렬을 구할 수 없는 행렬을 '특이 행렬' (Singular matrix)라고 합니다.  
크기가 3 x 3 이상인 행렬의 경우 보통 '가우스 소거법' Gaussian elimination 을 사용하여 역행렬을 구한다.  

!['가우시안 소거법'](https://wikimedia.org/api/rest_v1/media/math/render/svg/65c5c95d6260b9701d259277bc165ce6e5d1acf3)
https://ko.wikipedia.org/wiki/%EA%B0%80%EC%9A%B0%EC%8A%A4_%EC%86%8C%EA%B1%B0%EB%B2%95


In [54]:
# 넘파이에서는 'inv 함수'를 사용하여 역행렬을 구한다.
import numpy as np

A = np.array([[-1,1,2],
              [0,2,7],
              [0,2,2]
             ])
A

array([[-1,  1,  2],
       [ 0,  2,  7],
       [ 0,  2,  2]])

In [55]:
invA = np.linalg.inv(A)
invA

array([[-1. ,  0.2,  0.3],
       [ 0. , -0.2,  0.7],
       [-0. ,  0.2, -0.2]])

In [57]:
# A * invA 가 I 임을 확인
# 파이썬에서 결과 값이 근사값으로 출력되기 떄문에 
# np.round 를 사용하여 함수를 사용 한다.
print(np.dot(A,invA))

# round 함수를 사용하면 항등 행렬로 보임
print(np.round(np.dot(A,invA)))

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  5.55111512e-17]
 [ 0.00000000e+00 -5.55111512e-17  1.00000000e+00]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
